# Generated by Django 4.2.14 on 2024-10-22 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(unique=True, validators=[django.core.validators.RegexValidator(message='Номер должен состоять из 11 цифр.', regex='^\\d{11}$')], verbose_name='Номер телефона')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.user_avatar_directory_path, verbose_name='Аватарка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profile',
            },
        ),
    ]
