# Generated by Django 4.2.14 on 2024-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirm_required', 'Требуется подтверждение'), ('confirmed', 'Подтверждён'), ('paid', 'Оплачен'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('cancel', 'Отменён')], default='confirm_required', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
