# Generated by Django 4.2.14 on 2024-11-15 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар заказа', 'verbose_name_plural': 'Проданные товары'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Владелец карты')),
                ('number', models.CharField(validators=[django.core.validators.RegexValidator(message='Номер  должен быть не длиннее 8 цифр.', regex='^\\d{1,8}$')], verbose_name='Номер карты/счёта')),
                ('code', models.CharField(validators=[django.core.validators.RegexValidator(message='Код  должен состоять из 3 цифр.', regex='^\\d{3}$')], verbose_name='Код')),
                ('month', models.CharField(validators=[django.core.validators.RegexValidator(message='Введите номер месяца с карты.', regex='^[0]?[1-9]{1}$|^[1]{1}[0-2]{1}$')], verbose_name='month_valid_thru')),
                ('year', models.CharField(validators=[django.core.validators.RegexValidator(message='Год должен состоять из 4 цифр.', regex='^\\d{4}$'), orders.models.validate_expiry_period], verbose_name='year_valid_thru')),
                ('payment_error_message', models.TextField(blank=True, null=True, verbose_name='Текст ошибки оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата заказа',
                'verbose_name_plural': 'Оплаты заказов',
                'db_table': 'order_payment',
            },
        ),
    ]
