# Generated by Django 4.2.14 on 2024-11-18 15:51

import django.core.validators
from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_orderitem_options_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="code",
            field=models.CharField(
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Код  должен состоять из 3 цифр.", regex="^\\d{3}$"
                    )
                ],
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="month",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Введите номер месяца с карты.",
                        regex="^[0]?[1-9]{1}$|^[1]{1}[0-2]{1}$",
                    )
                ],
                verbose_name="month_valid_thru",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер  должен быть не длиннее 8 цифр.",
                        regex="^\\d{1,8}$",
                    )
                ],
                verbose_name="Номер карты/счёта",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="year",
            field=models.CharField(
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Год должен состоять из 4 цифр.", regex="^\\d{4}$"
                    ),
                    orders.models.validate_expiry_period,
                ],
                verbose_name="year_valid_thru",
            ),
        ),
    ]
