# Generated by Django 4.2.14 on 2024-11-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="dateFrom",
            field=models.DateField(verbose_name="Начало распродажи"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="dateTo",
            field=models.DateField(verbose_name="Конец распродажи"),
        ),
    ]
